# В этом месте вам необходимо настроить маршрутизацию /api/<resource>
server {
    listen 8080;
    location /api/devices {
        proxy_pass http://devices-svc-s15;
    }

    location /api/other {
        proxy_pass http://other-s15;
    }
}
