# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\ntickets.v1\"3\n\x13\x43reateTicketRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"@\n\x14\x43reateTicketResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x13\n\x11GetTicketsRequest\"9\n\x12GetTicketsResponse\x12#\n\x07tickets\x18\x01 \x03(\x0b\x32\x12.tickets.v1.Ticket\"2\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xb0\x01\n\x0eTicketsService\x12Q\n\x0c\x43reateTicket\x12\x1f.tickets.v1.CreateTicketRequest\x1a .tickets.v1.CreateTicketResponse\x12K\n\nGetTickets\x12\x1d.tickets.v1.GetTicketsRequest\x1a\x1e.tickets.v1.GetTicketsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETICKETREQUEST']._serialized_start=35
  _globals['_CREATETICKETREQUEST']._serialized_end=86
  _globals['_CREATETICKETRESPONSE']._serialized_start=88
  _globals['_CREATETICKETRESPONSE']._serialized_end=152
  _globals['_GETTICKETSREQUEST']._serialized_start=154
  _globals['_GETTICKETSREQUEST']._serialized_end=173
  _globals['_GETTICKETSRESPONSE']._serialized_start=175
  _globals['_GETTICKETSRESPONSE']._serialized_end=232
  _globals['_TICKET']._serialized_start=234
  _globals['_TICKET']._serialized_end=284
  _globals['_TICKETSSERVICE']._serialized_start=287
  _globals['_TICKETSSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
