global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tickets-service'
    static_configs:
      - targets: ['tickets-service:8124']

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8125']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8126']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
