# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\torders.v1\"4\n\x12\x43reateOrderRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"A\n\x13\x43reateOrderResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"\x12\n\x10GetOrdersRequest\"5\n\x11GetOrdersResponse\x12 \n\x06orders\x18\x01 \x03(\x0b\x32\x10.orders.v1.Order\"3\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"\x12\n\x10SubscribeRequest\"I\n\x0bOrderUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t2\xf1\x01\n\rOrdersService\x12L\n\x0b\x43reateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x1e.orders.v1.CreateOrderResponse\x12\x46\n\tGetOrders\x12\x1b.orders.v1.GetOrdersRequest\x1a\x1c.orders.v1.GetOrdersResponse\x12J\n\x11SubscribeToOrders\x12\x1b.orders.v1.SubscribeRequest\x1a\x16.orders.v1.OrderUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=34
  _globals['_CREATEORDERREQUEST']._serialized_end=86
  _globals['_CREATEORDERRESPONSE']._serialized_start=88
  _globals['_CREATEORDERRESPONSE']._serialized_end=153
  _globals['_GETORDERSREQUEST']._serialized_start=155
  _globals['_GETORDERSREQUEST']._serialized_end=173
  _globals['_GETORDERSRESPONSE']._serialized_start=175
  _globals['_GETORDERSRESPONSE']._serialized_end=228
  _globals['_ORDER']._serialized_start=230
  _globals['_ORDER']._serialized_end=281
  _globals['_SUBSCRIBEREQUEST']._serialized_start=283
  _globals['_SUBSCRIBEREQUEST']._serialized_end=301
  _globals['_ORDERUPDATE']._serialized_start=303
  _globals['_ORDERUPDATE']._serialized_end=376
  _globals['_ORDERSSERVICE']._serialized_start=379
  _globals['_ORDERSSERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
