replicaCount: 2
image:
  repository: invoices-s15
  tag: "latest"
service:
  name: invoices-svc-s15
  port: 8248
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
